# -*- coding: utf-8 -*-
"""PMU_feature_extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wJySPvIcSvPiiXaD2im8cCNKfoO8zWSj
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

from google.colab import files

uploaded = files.upload()

df=pd.read_csv('/content/pmu_data_RAW.csv')
df.head()

df.drop(columns=['tcp_window'],inplace=True)

col=df.columns
for i in col:
  print(i)

df.describe()

# Identify phasor columns (assuming all columns starting with IA_, IB_, or IC_ are phasor-related)
phasor_cols = [col for col in df.columns if col.startswith(('IA_', 'IB_', 'IC_'))]

# Identify timing feature columns
timing_cols = ['time', 'timestamp', 'time_base', 'timequality_mult', 'timequality_ns', 'timequality_ver']

# Identify signal statistics columns (assuming 'stat_data_sorting' is the relevant one)
signal_statistics_cols = ['stat_data_sorting']

# Combine all identified columns. Note: 'frequency' and 'dfreq' were not explicitly found by name.
selected_features_cols = phasor_cols + timing_cols + signal_statistics_cols

# Create the new DataFrame with only the selected features
features_df = df[selected_features_cols]

# Display the first few rows of the new DataFrame
print(f"New DataFrame shape: {features_df.shape}")
display(features_df.head())



mag_ang_cols = [
    'IA_ang', 'IA_mag', 'IB_ang', 'IB_mag', 'IC_ang', 'IC_mag',
    'VA_ang', 'VA_mag', 'VB_ang', 'VB_mag', 'VC_ang', 'VC_mag'
]

existing_mag_ang_cols = [col for col in mag_ang_cols if col in df.columns]
new_df = df[existing_mag_ang_cols]

# Display the first few rows of the new DataFrame
print(f"New DataFrame shape: {new_df.shape}")
display(new_df.head())

df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')
new_df['timestamp'] = df['timestamp']
new_df['FREQ'] = pd.to_numeric(df['freq1'], errors='coerce')
new_df['ROCOF'] = pd.to_numeric(df['dfreq1'], errors='coerce')
# time diff between dataframes
new_df['inter_arrival_time'] = (
    new_df['timestamp']
    .diff()
    .dt.total_seconds().fillna(0)
)

new_df.head()

new_df['VAB_angle_diff'] = (
    new_df['VA_ang'] - new_df['VB_ang']
)

new_df['VBC_angle_diff'] = (
    new_df['VB_ang'] - new_df['VC_ang']
)

new_df['VCA_angle_diff'] = (
    new_df['VC_ang'] - new_df['VA_ang']
)

new_df['network_delay'] = (
    pd.to_datetime(df['frame_time']) -
    pd.to_datetime(df['capture_time'])
).dt.total_seconds()

new_df['delay_change'] = (
    new_df['network_delay']
    .diff()
    .fillna(0)
)

new_df['packet_size'] = df['packet_size']
new_df['payload_size'] = df['payload_size']
#new_df['ttl'] = df['ttl']
new_df['soc'] = df['soc']
new_df['fracsec'] = df['fracsec']

# Create current angle differences
new_df['IAB_angle_diff'] = new_df['IA_ang'] - new_df['IB_ang']
new_df['IBC_angle_diff'] = new_df['IB_ang'] - new_df['IC_ang']
new_df['ICA_angle_diff'] = new_df['IA_ang'] - new_df['IC_ang']



new_df['crc_ok'] = df['crc_ok']

new_df.columns

V_base=220 #kv
S_base=100 #MVA
I_base=262.4 #A
# I_base = S_base / (np.sqrt(3) * V_base)
# normalize data
nominal_freq=50
new_df['FREQ'] = (
    new_df['FREQ'] - nominal_freq
) / nominal_freq
max_rocof = 5.0
new_df['ROCOF'] = new_df['ROCOF'] / max_rocof
new_df['ROCOF_abs']=new_df['ROCOF'].abs()
new_df['freq_change'] = new_df['FREQ'].diff().fillna(0)
# Convert voltage magnitudes to per unit
new_df['VA_mag'] = new_df['VA_mag'] / (V_base)
new_df['VB_mag'] = new_df['VB_mag'] / (V_base)
new_df['VC_mag'] = new_df['VC_mag'] / (V_base)

# Convert current magnitudes to per unit
new_df['IA_mag'] = new_df['IA_mag'] / (I_base)
new_df['IB_mag'] = new_df['IB_mag'] / (I_base)
new_df['IC_mag'] = new_df['IC_mag'] / (I_base)

# Add delta voltage and delta current (difference from previous entry)
new_df['delta_VA_mag'] = new_df['VA_mag'].diff().fillna(0)
new_df['delta_VB_mag'] = new_df['VB_mag'].diff().fillna(0)
new_df['delta_VC_mag'] = new_df['VC_mag'].diff().fillna(0)
new_df['delta_IA_mag'] = new_df['IA_mag'].diff().fillna(0)
new_df['delta_IB_mag'] = new_df['IB_mag'].diff().fillna(0)
new_df['delta_IC_mag'] = new_df['IC_mag'].diff().fillna(0)

# Convert voltage angles to sine and cosine components
new_df['VA_ang_sin'] = np.sin(new_df['VA_ang'])
new_df['VA_ang_cos'] = np.cos(new_df['VA_ang'])
new_df['VB_ang_sin'] = np.sin(new_df['VB_ang'])
new_df['VB_ang_cos'] = np.cos(new_df['VB_ang'])
new_df['VC_ang_sin'] = np.sin(new_df['VC_ang'])
new_df['VC_ang_cos'] = np.cos(new_df['VC_ang'])

# Convert current angles to sine and cosine components
new_df['IA_ang_sin'] = np.sin(new_df['IA_ang'])
new_df['IA_ang_cos'] = np.cos(new_df['IA_ang'])
new_df['IB_ang_sin'] = np.sin(new_df['IB_ang'])
new_df['IB_ang_cos'] = np.cos(new_df['IB_ang'])
new_df['IC_ang_sin'] = np.sin(new_df['IC_ang'])
new_df['IC_ang_cos'] = np.cos(new_df['IC_ang'])

# Drop the original angle columns
angle_cols_to_drop = [
    'IA_ang', 'IB_ang', 'IC_ang',
    'VA_ang', 'VB_ang', 'VC_ang'
]
new_df = new_df.drop(columns=angle_cols_to_drop)

angle_diff_cols = [
    'VAB_angle_diff', 'VBC_angle_diff', 'VCA_angle_diff',
    'IAB_angle_diff', 'IBC_angle_diff', 'ICA_angle_diff'
]

for col in angle_diff_cols:
    rad = new_df[col]

    new_df[col + '_sin'] = np.sin(rad)
    new_df[col + '_cos'] = np.cos(rad)

new_df.drop(columns=angle_diff_cols, inplace=True)

new_df['voltage_imbalance'] = (
    new_df[['VA_mag', 'VB_mag', 'VC_mag']]
    .std(axis=1)
)

new_df['current_imbalance'] = (
    new_df[['IA_mag', 'IB_mag', 'IC_mag']]
    .std(axis=1)
)

new_df['avg_voltage'] = (
    new_df[['VA_mag', 'VB_mag', 'VC_mag']]
    .mean(axis=1)
)

new_df['avg_current'] = (
    new_df[['IA_mag', 'IB_mag', 'IC_mag']]
    .mean(axis=1)
)

fps = 60
expected_dt = 1.0 / fps
base_size = 22
num_phasors=6
bytes_per_phasor=8
expacted_payload_size=base_size +(num_phasors * bytes_per_phasor)
headers_size=54
expacted_packet_size=expacted_payload_size + headers_size

new_df['inter_arrival_time'] = (
    (new_df['inter_arrival_time'] - expected_dt)/expected_dt
)
new_df['packet_size_error'] = (
    (new_df['packet_size'] - expacted_packet_size)
    / expacted_packet_size
)
new_df['payload_size_error'] = (
    (new_df['payload_size'] - expacted_payload_size)
    / expacted_payload_size
)

# new_df['ttl'] /= 255.0
# new_df['ttl_change'] = (
#     new_df['ttl']
#     .diff()
#     .abs().fillna(0)
# )
new_df['soc_diff'] = (
    new_df['soc']
    .diff()
    .fillna(0)
)
new_df['soc_timing_error'] = (
    (new_df['soc_diff'] - expected_dt)
    / expected_dt
)
new_df['fracsec'] /= 1e6
new_df['fracsec_diff'] = (
    new_df['fracsec']
    .diff()
)
new_df.drop(columns=['soc'], inplace=True)
new_df.drop(columns=['timestamp'], inplace=True)

new_df.columns